pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub_id')
        IMAGE_NAME = "<your-dockerhub-username>/jenkins-demo"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/<your-user>/jenkins-docker-ci-cd.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test || echo "No tests found"'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:latest ."
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh "echo ${DOCKERHUB_PSW} | docker login -u ${DOCKERHUB_USR} --password-stdin"
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push ${IMAGE_NAME}:latest"
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop jenkins-demo || true
                docker rm jenkins-demo || true
                docker run -d -p 3000:3000 --name jenkins-demo ${IMAGE_NAME}:latest
                '''
            }
        }
    }
}
