pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub_id')
        IMAGE_NAME = "pon802283/jenkins-demo"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
        sh 'cd my-app && npm install'
            }
        }


        stage('Test') {
            steps {
                    sh 'cd my-app && npm test || echo "No tests found"'
                }
            }


        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:latest my-app'
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh "echo ${DOCKERHUB_PSW} | docker login -u ${DOCKERHUB_USR} --password-stdin"
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push ${IMAGE_NAME}:latest"
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop jenkins-demo || true
                docker rm jenkins-demo || true
                docker run -d -p 3000:3000 --name jenkins-demo ${IMAGE_NAME}:latest
                '''.replace("yourdockerhubusername", "${IMAGE_NAME}".split('/')[0])
            }
        }
    }

    post {
        success {
            echo "Deployment Success"
        }
        failure {
            echo "Deployment Failed"
        }
    }
}
